name = "reverse-proxy-worker-cloudflare"
main = "src/index.ts"
compatibility_date = "2022-05-12"
usage_model = "bundled"
send_metrics = false

[env.production]
name = "reverse-proxy-worker-cloudflare"

# [vars]
# token = "token123456"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
